from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any

import httpx

from .canon import format_canon_for_prompt, load_wiki_canon
from .paths import CONTENT_EPISODES, REPO_ROOT, RUNS_DIR, TOOLS_ROOT

OPENROUTER_API_URL = "https://openrouter.ai/api/v1/chat/completions"
DEFAULT_MODEL = "openrouter/free"
FALLBACK_MODELS = [
    "meta-llama/llama-3.3-70b-instruct:free",
    "google/gemma-4-31b-it:free",
    "nvidia/nemotron-3-super-120b-a12b:free",
]


def load_env() -> None:
    """Load .env from tools/.env or REPO_ROOT/.env if present."""
    for env_path in [TOOLS_ROOT / ".env", REPO_ROOT / ".env"]:
        if env_path.exists():
            for line in env_path.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, val = line.split("=", 1)
                key = key.strip()
                val = val.strip().strip("'\"")
                if key not in os.environ:
                    os.environ[key] = val


def get_api_key() -> str:
    load_env()
    key = os.environ.get("OPENROUTER_API_KEY", "").strip()
    if not key:
        raise SystemExit(
            "\n[Error] OPENROUTER_API_KEY is not set.\n"
            "To use OpenRouter extraction (including free models):\n"
            "  1. Get an API key from https://openrouter.ai/keys\n"
            "  2. Add it to tools/.env:\n"
            "       OPENROUTER_API_KEY=sk-or-v1-...\n"
            "  3. Or export it in your environment:\n"
            "       export OPENROUTER_API_KEY=sk-or-v1-...\n"
        )
    return key


SYSTEM_PROMPT = """You are the canon lore archivist for 'Barely Informed News' (BIN), an online satirical news show stream on Twitch (twitch.tv/caseblackwell).

Key show context:
- Host: Case Blackwell.
- Characters: All on-air characters are played by Case Blackwell himself using face filters and voice changers.
- Tone: Irreverent satire, absurd storylines, rapid-fire bits.
- Famous bits / storylines: Munch vs Crum debate (a heated, recurring rivalry between two debate-panel personas: Munch and Crum).
- Note on ASR transcription: The input transcript was generated by automated speech recognition (Whisper). Names may have phonetic variations (e.g. "Crumb" for "Crum", "Monch" for "Munch"). Reconcile them to known canon entities when possible.

Your task:
Analyze the provided stream transcript and extract:
1. "segments": Major show segments with start and end timestamps (e.g. "MM:SS" or "HH:MM:SS"), a title, and concise notes.
2. "characters": Characters detected on stream (either speaking in-character via voice changer / face filter, or heavily discussed/slandered). Mark whether they were actively speaking or merely mentioned, with timestamps.
3. "storylines": Developments, escalations, or callbacks to ongoing storylines (especially the Munch–Crum rivalry) or new arcs.
4. "lore_notes": Meaningful canonical lore facts, character backstories, relationships, catchphrases, or recurring gags. Do NOT include generic one-off news jokes. Every lore note MUST include an exact source timestamp like "[49:58]".
5. "episode_summary": A 2-3 sentence high-level overview of the stream.

Output format:
Respond ONLY with a valid JSON object matching this schema:
{
  "episode_summary": "...",
  "segments": [
    {
      "start": "00:00",
      "end": "16:00",
      "title": "...",
      "notes": "...",
      "characters": ["..."]
    }
  ],
  "characters": [
    {
      "name": "...",
      "canonical_name": "...",
      "speaking": true,
      "timestamps": ["..."],
      "confidence": 0.95,
      "notes": "..."
    }
  ],
  "storylines": [
    {
      "storyline": "Munch–Crum rivalry",
      "beat": "...",
      "timestamp": "..."
    }
  ],
  "lore_notes": [
    {
      "entity": "...",
      "fact": "...",
      "timestamp": "...",
      "confidence": 0.9
    }
  ]
}
"""


def build_user_prompt(meta: dict[str, Any], canon_text: str, transcript_text: str) -> str:
    return f"""### Stream Metadata
- Title: {meta.get('title', 'Unknown')}
- Date: {meta.get('date', 'Unknown')}
- Duration: {meta.get('duration', 'Unknown')}
- URL: {meta.get('url', 'Unknown')}

### Existing Wiki Canon Roster
{canon_text}

### Stream Transcript (with timestamps)
{transcript_text}
"""


def _parse_llm_json(text: str) -> dict[str, Any]:
    text = text.strip()
    # Try direct parse
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Try extracting from markdown code block ```json ... ```
    match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", text)
    if match:
        try:
            return json.loads(match.group(1).strip())
        except json.JSONDecodeError:
            pass

    # Try finding outer braces
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        try:
            return json.loads(text[start : end + 1])
        except json.JSONDecodeError:
            pass

    raise ValueError(f"Could not parse valid JSON from LLM response:\n{text[:500]}...")


def query_openrouter(
    prompt: str,
    *,
    api_key: str,
    models: list[str],
    timeout: float = 180.0,
) -> tuple[dict[str, Any], str]:
    """Query OpenRouter, trying models in order if errors occur."""
    headers = {
        "Authorization": f"Bearer {api_key}",
        "HTTP-Referer": "https://github.com/trak3r/binlore",
        "X-Title": "Binlore Wiki Pipeline",
        "Content-Type": "application/json",
    }

    last_error: Exception | None = None
    for model in models:
        print(f"Querying OpenRouter model: {model}...", flush=True)
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            "temperature": 0.2,
        }

        try:
            with httpx.Client(timeout=timeout) as client:
                resp = client.post(OPENROUTER_API_URL, headers=headers, json=payload)

            if resp.status_code != 200:
                print(f"  Model {model} returned HTTP {resp.status_code}: {resp.text[:200]}", flush=True)
                last_error = RuntimeError(f"HTTP {resp.status_code}: {resp.text}")
                continue

            data = resp.json()
            choices = data.get("choices") or []
            if not choices:
                last_error = RuntimeError(f"No choices returned: {data}")
                continue

            content = choices[0].get("message", {}).get("content", "")
            parsed = _parse_llm_json(content)
            return parsed, model
        except Exception as e:
            print(f"  Model {model} failed: {e}", flush=True)
            last_error = e

    raise RuntimeError(f"All requested models failed. Last error: {last_error}")


def extract_lore_from_vod(
    vod_id: str,
    *,
    model: str = DEFAULT_MODEL,
    dry_run: bool = False,
) -> dict[str, Any]:
    run_dir = RUNS_DIR / vod_id
    if not run_dir.exists():
        raise SystemExit(f"Run directory not found: {run_dir}. Did you run `binlore ingest` first?")

    transcript_path = run_dir / "transcript.txt"
    if not transcript_path.exists():
        raise SystemExit(f"Transcript not found: {transcript_path}")

    meta_path = run_dir / "meta.json"
    meta: dict[str, Any] = {}
    if meta_path.exists():
        try:
            meta = json.loads(meta_path.read_text(encoding="utf-8"))
        except Exception:
            pass

    transcript_text = transcript_path.read_text(encoding="utf-8")
    canon_text = format_canon_for_prompt()
    user_prompt = build_user_prompt(meta, canon_text, transcript_text)

    if dry_run:
        print("\n--- [DRY RUN: Prompt Preview] ---")
        print(f"System Prompt Length: {len(SYSTEM_PROMPT)} chars")
        print(f"User Prompt Length: {len(user_prompt)} chars (~{len(user_prompt)//4} tokens)")
        print("\nFirst 1000 chars of User Prompt:")
        print(user_prompt[:1000])
        print("--- [END DRY RUN] ---\n")
        return {"dry_run": True}

    api_key = get_api_key()
    models_to_try = [model]
    for m in FALLBACK_MODELS:
        if m not in models_to_try:
            models_to_try.append(m)

    extracted_data, used_model = query_openrouter(
        user_prompt,
        api_key=api_key,
        models=models_to_try,
    )

    extracted_data["_meta"] = {
        "vod_id": vod_id,
        "model": used_model,
        "transcript_lines": len(transcript_text.splitlines()),
    }

    # Save extraction JSON
    out_path = run_dir / "extraction.json"
    out_path.write_text(json.dumps(extracted_data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Saved extraction results to {out_path}", flush=True)

    # Update episode markdown page in content/episodes/
    from .episode import update_episode_from_extraction
    ep_path = update_episode_from_extraction(vod_id, extracted_data)
    print(f"Updated episode page: {ep_path.relative_to(REPO_ROOT)}", flush=True)

    return extracted_data
